name: Test, Build and Deploy project
on: [push]
jobs:
  Deploy-Porject:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Installing dependencies
        run: npm ci

      - name: Lint code
        run: npm lint

      - name: Test code
        run: npm test

      - name: Build code
        run: npm build

      - name: Deploy code
        run: echo "Deploying code"