name: Test, Build and Deploy project
on:
  push:
    branches:
      - main
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run test
        run: npm run test

  build-project:
    runs-on: ubuntu-latest
    needs: test-project
    outputs:
      script-file: ${{ steps.output-step.outputs.script-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Output build filename
        id: output-step
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist

  deploy-project:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Output file name
        run: echo "${{ needs.build-project.outputs.script-file }}"
      - name: Deploy project
        run: echo "Deploying project"
