name: Run test on pull request
on:
  pull_request:
    types:
      - opened
    branches:
      - dev
  workflow_dispatch:
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm run test